{
    "apiVersion": "extensions/v1beta1",
    "kind": "Deployment",
    "metadata": {
        "annotations": {
            "deployment.kubernetes.io/revision": "1"
        },
        "creationTimestamp": null,
        "generation": 1,
        "labels": {
            "k8s-app": "spike"
        },
        "name": "spike",
        "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/spike"
    },
    "spec": {
        "progressDeadlineSeconds": 600,
        "replicas": 1,
        "revisionHistoryLimit": 10,
        "selector": {
            "matchLabels": {
                "k8s-app": "spike"
            }
        },
        "strategy": {
            "rollingUpdate": {
                "maxSurge": "25%",
                "maxUnavailable": "25%"
            },
            "type": "RollingUpdate"
        },
        "template": {
            "metadata": {
                "creationTimestamp": null,
                "labels": {
                    "k8s-app": "spike"
                },
                "name": "spike"
            },
            "spec": {
                "containers": [
                    {
                        "env": [
                            {
                                "name": "PORT",
                                "value": "8000"
                            }
                        ],
                        "image": "localhost:5000/spike",
                        "imagePullPolicy": "Always",
                        "name": "spike",
                        "resources": {},
                        "securityContext": {
                            "privileged": false
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File"
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "terminationGracePeriodSeconds": 30
            }
        }
    },
    "status": {}
}
